name: CI

on:
  push:
    branches:
      - '**'  # Ejecutar en cualquier rama
  pull_request:
    branches:
      - '**'  # Ejecutar en pull requests a cualquier rama

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Esto habilita la distribución de tareas a través de Nx Cloud
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache de node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      # Ejecutar lint, test y build en base a los cambios en el PR o commit
      - run: npx nx affected -t lint test build
